### PR TITLE
Spon 29 advertise events

### PR DESCRIPTION
**Pull request by NadhiyaNashath**
spon 29 ads listing page done for university client. along with that spon 80 selected ads page is also done in the same branch since both are related (it was taken from the backlog).

### CODE REVIEW

**Review by Risafamtii — APPROVED** [review]
i checked

**Comment by JAbasith** [comment]
I checked

**Review by JAbasith — COMMENTED** [review]
good job

**Review by HashirAhamed — APPROVED** [review]

**Comment by Amrah444** [comment]
Good Baba

**Review by AthharPro — APPROVED** [review]

**Review by Amrah444 — APPROVED** [review]

**Pull request merged**
